{
 "title": "Mocha Optimization & High Performance - Healthcare Client Benefits Application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage (RSS) - Lower is Better",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_rss{name=\"primes-openjdk\"}",
     "legendFormat": "Memory / OpenJDK"
    },
    {
     "expr": "container_memory_rss{name=\"primes-native-g1\"}",
     "legendFormat": "Memory / Native Image"
    }
   ]
  },
  {
   "title": "Memory Usage Improvement",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_rss{name=\"primes-native-g1\"}) - sum(container_memory_rss{name=\"primes-openjdk\"})) / sum(container_memory_rss{name=\"primes-openjdk\"}) * -100"
    }
   ]
  },
  { "title": "Startup Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Start-up Time - Lower is Better",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_started_time_seconds{job=\"primes.openjdk\"}",
     "legendFormat": "Startup / OpenJDK"
    },
    {
     "expr": "application_started_time_seconds{job=\"primes.native-g1\"}",
     "legendFormat": "Startup / Native Image"
    }
   ]
  },
  {
   "title": "Startup Time Improvement",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(application_started_time_seconds{job=\"primes.native-opt\"}) - sum(application_started_time_seconds{job=\"primes.openjdk\"})) / sum(application_started_time_seconds{job=\"primes.openjdk\"}) * -100"
    }
   ]
  },
  { "title": "Application Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Throughput - Higher is Better",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"primes.openjdk\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "OpenJDK (req / s)"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"primes.graalee\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "GraalVM EE (req / s)"
    }
   ]
  }
 ]
}