{
 "title": "Service Level / Customer Portfolio Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage (RSS)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_rss{name=\"primes-native-g1\"}",
     "legendFormat": "Memory / Native Image"
    },
    {
     "expr": "container_memory_rss{name=\"primes-openjdk\"}",
     "legendFormat": "Memory / OpenJDK"
    }
   ]
  },
  {
   "title": "Start-up Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_started_time_seconds{job=\"primes.native-g1\"}",
     "legendFormat": "Native Image Startup"
    },
    {
     "expr": "application_started_time_seconds{job=\"primes.openjdk\"}",
     "legendFormat": "OpenJDK Startup"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"primes.openjdk\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "OpenJDK (req / s)"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"primes.native-opt\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "Native Image  (req / s)"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"primes.native-g1\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "Native Image G1 (req / s)"
    }
   ]
  }
 ]
}