{
 "title": "Overall Perfomance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Baseline Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  {
   "title": "CPU Usage (Baseline)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[$__interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{cpu=\"(0|1)\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)",
     "legendFormat": "Baseline"
    }
   ]
  },
  {
   "title": "RAM Usage (Baseline)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemFree_bytes{job=\"node\"}) / node_memory_MemTotal_bytes{job=\"node\"}) *100"
    }
   ]
  },
  {
   "title": "Requests Per Second (Baseline)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"spring-actuator\"}[$__interval])",
     "legendFormat": "Baseline"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  { "title": "Optimized Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  {
   "title": "CPU Usage (Optimized)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[$__interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{cpu=\"(0|1)\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)",
     "legendFormat": "OpenJDK"
    }
   ]
  },
  {
   "title": "RAM Usage (Optimized)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemFree_bytes{job=\"node\"}) / node_memory_MemTotal_bytes{job=\"node\"}) *100"
    }
   ]
  },
  {
   "title": "Requests Per Second (Optimized)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"spring-actuator\"}[$__interval])",
     "legendFormat": "Optimized"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Comparing Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Baseline)",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[$__interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{cpu=\"(0|1)\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU Usage (Optimized)",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[$__interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{cpu=\"(0|1)\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)",
       "legendFormat": "GraalVM"
      }
     ]
    },
    {
     "title": "CPU Usage (Combined)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[1m]),1)) or (clamp_max(irate(node_cpu_seconds_total{cpu=\"(0|1)\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
      },
      {
       "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[1m]),1)) or (clamp_max(irate(node_cpu_seconds_total{cpu=\"(0|1)\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
      }
     ]
    },
    {
     "title": "Used RAM (Baseline)",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemFree_bytes{job=\"node\"}) / node_memory_MemTotal_bytes{job=\"node\"}) *100"
      }
     ]
    },
    {
     "title": "Used RAM (Optimized)",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemFree_bytes{job=\"node\"}) / node_memory_MemTotal_bytes{job=\"node\"}) *100"
      }
     ]
    },
    {
     "title": "RAM Usage (Combined)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemFree_bytes{job=\"node\"}) / node_memory_MemTotal_bytes{job=\"node\"}) *100",
       "legendFormat": "Baseline"
      },
      {
       "expr": "((node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemFree_bytes{job=\"node\"}) / node_memory_MemTotal_bytes{job=\"node\"}) *100",
       "legendFormat": "Optimized"
      }
     ]
    },
    {
     "title": "Requests Per Second (Combined)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{job=\"spring-actuator\"}[1m])",
       "legendFormat": "Baseline"
      },
      {
       "expr": "rate(http_server_requests_seconds_count{job=\"spring-actuator\"}[1m])",
       "legendFormat": "Optimized"
      }
     ]
    }
   ]
  },
  { "title": "Container Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Containers (Node 1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".*.\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Load (Node 1)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Load (Node 1)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used Memory (Node 1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Containers (Node 2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".*.\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Load (Node 2)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Load (Node 2)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used Memory (Node 2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"primes:jdk\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "Node 1: {{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "Node 2: {{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image=\"primes:jdk\"})",
     "legendFormat": "Node 1: {{ name }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "Node 2: {{ name }}"
    }
   ]
  }
 ]
}